### ISSUE TITLE
No link or instructions for rebuilding u-boot

### ISSUE THREAD

**Issue by jadonk** [ravikp7/node-beagle-boot#16]
Having randomly working binaries isn't acceptable. We need to know how they were built.

I'd like to patch your u-boot with one that will take netconsole commands and use the netconsole commands to enter UMS mode, rather than enter it directly.... at least not without a timeout period. This would allow arbitrary u-boot commands to be executed, potentially changing the mmc to export, enabling us to probe various hardware features and more.

**Comment by ravikp7** [comment]
The reason I didn't provide info on how I built binaries as earlier I couldn't get the upstream uboot working with this server. But now, with the help of @abhishek-kakkar I got it working with upstream uboot. It's in dev branch [here](https://github.com/ravikp7/node-beagle-boot/tree/dev) 
Instructions for uboot build:
Enable [these](https://www.irccloud.com/pastebin/0MOcvEOA/) in am335x_evm_defconfig for spl and build it.
As am335x_evm_usbspl_defconfig isn't working :(

**Comment by jadonk** [comment]
Reason not to post them here?

```
CONFIG_SPL_NET_SUPPORT=y
CONFIG_SPL_USB_GADGET_SUPPORT=y
CONFIG_SPL_USBETH_SUPPORT=y
CONFIG_SPL_NET_VCI_STRING="AM335x U-Boot SPL"
CONFIG_NET_RANDOM_ETHADDR=y
```

**Comment by jadonk** [comment]
Which commit works? Which compiler?

When you say "it's in dev branch", do you mean that fix or do you mean the instructions?

**Comment by ravikp7** [comment]
The fix that works with upstream u-boot is in dev branch. Instructions: https://github.com/ravikp7/node-beagle-boot/tree/dev#u-boot-binary-build-instructions

**Comment by jadonk** [comment]
Also, exactly which files are chosen, since  you rename them!
